---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Connectivity Test ping to Target Server (IP)
      command: "podman exec -it rhel8 ping -c 1 -W 3 rhel8" 
