---
dependency:
  name: galaxy
provisioner:
  name: ansible
driver:
  name: podman
platforms:
  - name: centos_os
    image: quay.io/centos/centos:stream8
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
