---
dependency:
  name: galaxy
provisioner:
  name: ansible
driver:
  name: podman
platforms:
  - name: centos_os
    image: quay.io/centos/centos:stream8
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint

# ---
# dependency:
#   name: galaxy
# driver:
#   name: docker
# platforms:
#   - name: instance
#     image: quay.io/centos/centos:stream8
#     pre_build_image: true
#     command: /sbin/init
#     tmpfs:
#       - /run
#       - /tmp
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
# provisioner:
#   name: ansible
#   env:
#     ANSIBLE_COLLECTIONS_PATH: "../../../../../" # when molecule inside the roles inside a collection

# verifier:
#   name: ansible
