---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: mcr.microsoft.com/windows:ltsc2019
    docker_host: 'tcp://192.168.0.27:2375'
    command: "powershell 'while (1 -eq 1) {Start-Sleep -s 1000}'"
    exposed_ports: ["5985","5986"]
    published_ports: ["5985:5985","5986:5986"]
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: 'bharat'
        ansible_password: '8612'
        ansible_connection: winrm
        ansible_winrm_port: '5985'
        ansible_winrm_scheme: 'http'
        ansible_winrm_server_cert_validation: 'ignore'
        ansible_host: '192.168.0.27'
verifier:
  name: inspec