---
- name: Include a role from a collection
  hosts: centos_os
  gather_facts: false
  #become: true
  tasks:
    - name: Testing role File copy
      include_role:
        name: /home/ansible/actions-runner/_work/ansible_roles_testing/ansible_roles_testing/roles/file_copy/
        tasks_from: main.yml
