- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yaml"
 
- name: Ensure package cache up-to-date
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
 
- name: Ensure httpd installed
  package:
    name: "{{ httpd_package }}"
    state: present