---
- name: testing molecule ping role
  hosts: all
  gather_facts: false
  #become: true
  tasks:
    - name: Testing role
      include_role:
        name: /home/ansible/actions-runner/_work/ansible_roles_testing/ansible_roles_testing/roles/ping/
        tasks_from: main.yml
