name: Ansible Lint test 

"on":
  push:

jobs:
  Finding Ansible Lint Isuses:
    runs-on: self-hosted 

    outputs:
      get_roles: ${{ steps.get_changed_paths.outputs.ansible_roles }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      
  Ansible Lint Fix:
    runs-on: self-hosted 
  
    strategy:
      matrix:
        value: ${{ fromJSON(needs.find_changed_roles.outputs.get_roles) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
  Ansible Lint Fix QU Branch:
    runs-on: self-hosted 
  
    strategy:
      matrix:
        value: ${{ fromJSON(needs.find_changed_roles.outputs.get_roles) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  FInal Merge to Prod Branch:
    runs-on: self-hosted 
  
    strategy:
      matrix:
        value: ${{ fromJSON(needs.find_changed_roles.outputs.get_roles) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2